config/routes.rb
Rails.application.routes.draw do

  get 'events/new'

  get 'users/new'

  get 'events/new'

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get 'news'    => 'static_pages#news'
  get 'events'  => 'static_pages#events'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get 'create_event'  => 'events#new'

  get 'login'   => 'sessions#new'
  post'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :events # allow us to generate named routes

end

app/models/event.rb
class Event < ActiveRecord::Base
	# to validate presence of an attribute
	validates :name, presence: true, length: { minimum: 5} 

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :remember_token

	before_save { self.email = email.downcase }
	validates :name,  presence: true, length: { maximum: 50 }
  	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

	# Returns the hash digest of the given string.
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
	                                              BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	def User.new_token
		SecureRandom.urlsafe_base64
	end

	# Remembers a user in the database for use in persistent sessions.
  	def remember
    	self.remember_token = User.new_token
    	update_attribute(:remember_digest, User.digest(remember_token))
  	end

  	# Returns true if the given token matches the digest.
 	def authenticated?(remember_token)
 		return false if remember_digest.nil?
    	BCrypt::Password.new(remember_digest).is_password?(remember_token)
  	end

  	 # Forgets a user.
  	def forget
    	update_attribute(:remember_digest, nil)
  	end
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def hello
  	render text: "Hello! This is the club website template."
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :admin_present, only: [:new, :edit, :update]
	before_action :user_present, only: [:new, :edit, :update]


  # check if current user is an admin
  # only admin can make event etc
  def admin_present
    unless current_user.admin?
      flash[:danger] = "Please log in"
      redirect_to login_url
    end
  end

  def user_present
  	unless current_user.present?
 
  		flash[:danger] = "Please log in"
  		redirect_to login_url
  	end	
  end

  def new
  	# create Event object as argument for form_for
  	@event = Event.new 
  end

  def show 
  	@event = Event.find(params[:id]) # retreive id
  end

  def create
  	@event = Event.new(event_params) 
  	if @event.save
  		# Handle succesful save
  		flash[:success] = "Event " + @event.name + " was created!" 
  		redirect_to @event
  	else
  		render 'new' # events#new page (with flash)
  	end
  end

  def edit
  	@event = Event.find(params[:id])
  	
  end

  def update
  	@event = Event.find(params[:id])
  	if @event.update_attributes(event_params)
  		flash[:success] = "Event information updated"
  		redirect_to @event
  	else
  		render 'edit'
  	end
  end

  private

  	def event_params
  		params.require(:event).permit(:name)
  	end
 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		# log in
  		log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
  		redirect_back_or user
  	else
  		flash.now[:danger] = 'Invalid email/password combination'
  		render 'new'
  	end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController


  def home
  	
  end

  def news
  end

  def events
  	@events = Event.all
  end
  
  def contact
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def show
  	@user = User.find(params[:id])
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
  	# @ sign creates a variable
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      log_in @user
      flash[:success] = "Welcome."
      redirect_to @user
  		# successful signup, handle
  	else
  		render 'new'
  	end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end


  def edit
    # get the user from database whos data we want to edit
  end

  def update
    if @user.update_attributes(user_params)
      # handle successful update
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Return the full title on per page basis.
	# In the case a title is not provided in .html.erb 
	# using <% provide... %>

	def full_title(page_title = '')
		base_title = "QUT Japan"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
	
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	# Remembers a user in a persistent session.
  	def remember(user)
	    user.remember
	    cookies.permanent.signed[:user_id] = user.id
	    cookies.permanent[:remember_token] = user.remember_token
 	end

 	def current_user?(user)
 		user == current_user
 	end

	def log_out
		forget(current_user)	
		session.delete(:user_id)
		@current_user = nil
	end

	def current_user
		if (user_id = session[:user_id])
      		@current_user ||= User.find_by(id: user_id)
    	elsif (user_id = cookies.signed[:user_id])
      		user = User.find_by(id: user_id)
	      	if user && user.authenticated?(cookies[:remember_token])
	        	log_in user
	        	@current_user = user
	      	end
    	end
	end

	# redirect to stored location
	def redirect_back_or(default)
		redirect_to(session[:forwarding_url] || default)
		session.delete(:forwarding_url)
	end

	# store url trying to be accessed
	def store_location
		session[:forwarding_url] = request.url if request.get?
	end

	# Forgets a persistent session.
  	def forget(user)
	    user.forget
	    cookies.delete(:user_id)
	    cookies.delete(:remember_token)
  	end

	def logged_in?
		!current_user.nil?
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<% provide(:title, "Edit event information") %>
<h1>Update event information</h1>

<div class="row">
	<%= form_for(@event) do |f| %>
		<%= render 'shared/event_error_messages' %>
		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control' %>

		<%= f.submit "Save changes", class: 'btn btn-primary' %>
	<% end %>
</div>

app/views/events/new.html.erb
<% provide(:title, "Make new event") %>
<h1>Create new event</h1>

<div class="row">
	<%= form_for(@event) do |f| %>
		<%= render 'shared/event_error_messages' %>
		<%= f.label :name %> 
		<!-- form control is a bootstrap class --> 
		<%= f.text_field :name, class: 'form-control' %> 

		<%= f.submit "Upload event", class: "btn btn-primary" %>
	<% end %>
</div>

app/views/events/show.html.erb
<div class="events">
	<%= @event.name %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		QUT Japan homepage by Lachlan Miller
	</small>
	<nav>
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav> 
</footer>

app/views/layouts/_header.html.erb
<!--  three classes, separated by spaces  -->
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "QUT Japan", root_path, id: "logo" %>
		<nav> <!-- navigation links -->
			<!-- ul is unordered list -->
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "News", news_path %></li> 
				<li><%= link_to "Events", events_path %></li>

				<% if logged_in? %>
					<li><%= link_to "Users", users_path %></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
	            		<ul class="dropdown-menu">
							<li><%= link_to "Profile", current_user %></li>
							<li><%= link_to "Settings", edit_user_path(current_user) %></li>
							<li class="divider"></li>
							<li><%= link_to "Log out", logout_path, method: "delete" %></li>
						</ul>
					</li>
				<% else %>
					<li><%= link_to "Staff Login", login_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>

</head>
	<body>
		<!-- see app/views/layouts for the code, partials always preceeded by _, [an underscore] -->
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |message_type, message| %>
      			<div class="alert alert-<%= message_type %>"><%= message %></div>
      		<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_event_error_messages.html.erb
<% if @event.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@event.errors.count, "error") %>.
    </div>
    <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
	Contact us at qut.japan1503@gmail.com.
</p>

app/views/static_pages/events.html.erb
<% provide(:title, "Events") %>
<h1>Events</h1>
<p>
	Events info goes here.
</p>

<div class="row">

	<% @events.each do |event|  %>
		<ul>
			<%= link_to event.name, event %>
		</ul>
	
	<% end %>

	<% if logged_in? && current_user.admin? %>

		<%= link_to "Create event", create_event_path, class: "btn btn-primary" %>
	<% end %>
</div>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
	<h1>Home</h1>
	<h2>
		This is the homepage for <a href="https://www.facebook.com/groups/qut.japan1503/">QUT Japan.</a>
	</h2>

	<%= link_to "Sign Up", signup_path, class: "btn btn-lg btn-primary" %>

</div>

<h1>
<%= link_to image_tag("qutjapan.png", alt: "QUT Japan logo"), 'https://www.facebook.com/groups/qut.japan1503/'  %>
</h1>

app/views/static_pages/news.html.erb
<% provide(:title, "News") %>
<h1>News</h1>
<p>
	Learn about past and upcoming events.
</p>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<h1>Update your profile</h1>

<div class="row"> 
	<div class="col-md-6 col-md-offset-3"> 
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :name %> <!-- this line appears on screen -->
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control'%>

			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>

			<%= f.submit "Save Changes", class: "btn btn-primary" %>

		 <% end %>
	</div> 
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
	<% @users.each do |user| %>
		<li>
			<%= link_to user.name, user %>
			<% if current_user.admin? && !current_user?(user) %> 
				<%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
			<% end %>
		</li>
	<% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row"> 
	<div class="col-md-6 col-md-offset-3"> 
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :name %> <!-- this line appears on screen -->
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control'%>

			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>

			<%= f.submit "Create Account", class: "btn btn-primary" %>

		 <% end %>
	</div> 
</div>

app/views/users/show.html.erb
<div class="field">
<!--
	<%= @user.name %>, <%= @user.email %> 
-->
<h3>Welcome, <%= @user.name %></h3>
</div>